config/routes.rb
Blog::Application.routes.draw do
  devise_for :users
  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :profiles
  resources :posts

  get "home/index"
  root :to => "home#index"
  resources :posts do
  resources :comments

 end
  

   match ':controller(/:action(/:id(.:format)))'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates_presence_of :body
  attr_accessor:countTest
end

app/models/post.rb
class Post < ActiveRecord::Base

  acts_as_taggable #标签

  validates_numericality_of  :category
  validates :category,  :presence => true
  validates :title, :presence => true,
                    :length => { :minimum => 2 }
 has_many :comments, :dependent => :destroy
 has_many :tags
  belongs_to:user
 accepts_nested_attributes_for :tags, :allow_destroy => :true,
    :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
end

app/models/profile.rb
class Profile < ActiveRecord::Base
   belongs_to :user

  validates_numericality_of(:birth_year,:only_integer => true,:greater_than => 1963, :less_than => 2012 ,:allow_blank => true ,:message => '1963-2011')
  validates_numericality_of(:birth_month,:only_integer => true,:greater_than =>0,:less_than =>13 ,:allow_blank => true ,:message => '1-12')
  validates_presence_of :birth_year, :birth_month, :birth_day,:on => :update      #不能为空验证
  validates_numericality_of :birth_year,:birth_month,:birth_day ,:allow_blank => true   #不能为非数字验证

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login
  # Setup accessible (or protected) attributes for your model
  attr_accessible  :login,:email, :password, :password_confirmation, :remember_me,:username,
          :role,:avatar
  has_one:profile
  has_many:posts
  has_many:comments
  #validates_associated :profile  # 查验指定的对象。

 after_create :set_profile
   def set_profile
     @profile = self.build_profile
   end

 protected
   def self.find_for_database_authentication(warden_conditions)    #指定用户名或email登录
   conditions = warden_conditions.dup
   login = conditions.delete(:login)
   where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.strip.downcase }]).first
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
    def after_sign_in_path_for(resource)
        return request.env['omniauth.origin'] || stored_location_for(resource) || posts_path
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user! , :except => [:show]     #没有登录直接跳到登录界面

def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(params[:comment])
    @comment.update_attributes(:user_id=>current_user.id)
      if   @comment.save
           @comment.countTest=comment_count
        respond_to do |format|
         format.js
         end
      end
end

def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
   # redirect_to post_path(@post)
     @comment.countTest=comment_count
  respond_to do |format|
      format.js
    end
end

  protected              #查询评论数量
   def comment_count
            @number=@post.comments.count
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   #before_filter :authenticate_user! , :except => [:show]     #没有登录直接跳到登录界面
  def index
     @posts = Post.order("created_at desc").page(params[:page]).per(4)
      tag_cloud #加入标签云
     respond_to do |format|
     format.html # index.html.erb
    end
  end

    def tag_cloud
    @tags = Post.tag_counts_on(:tags)
  end

  def tag
       @posts= Post.tagged_with(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user! , :except => [:show]     #没有登录直接跳到登录界面
  def index

        @search  = Post.search(params[:search])
        @posts = @search.all     #查出所有匹配的记录
        @posts = @search.page(params[:page]).per(2)
               if  params[:search]==nil
                 @posts = Post.where(:user_id=>current_user.id).page(params[:page]).per(2)
               end
       tag_cloud #加入标签云
      respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def tag_cloud
    @tags = Post.tag_counts_on(:tags)
  end

  def tag
       @posts= Post.tagged_with(params[:id])
end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    respond_to do |format|
        format.html
        format.js
      end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.user_id=current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :ok }
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
       before_filter :authenticate_user! , :except => [:show]     #没有登录直接跳到登录界面
  def create
    @profile = @profile.users.create(params[:id])
   # @profile = @user.build_profile
    redirect_to post_path(@post)
  end

   def edit
    @profile = Profile.find(params[:id])
   end

  def new
  end

  def show
  end

   def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'profile was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
 def join_tags(post)
    post.tags.map { |t| t.name }.join(", ") 
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/comments/_comment.html.erb
<tr id="<%= dom_id comment %>">
     <td><%= comment.user.username %></td>
     <td><%= comment.body %></td>
     <td><%= time_ago_in_words(comment.created_at) %></td>
      <td><%= link_to 'Destroy Comment', [comment.post, comment], :confirm => 'Are you sure?',:method => :delete  , :remote => true %></td>
</tr>

app/views/comments/_countcomments.html.erb
<div id="total">
  共有<%=@comment.countTest%>条回复
 </div>

app/views/comments/create.js.erb
$('<%= escape_javascript(render(:partial => @comment)) %>').appendTo('#comments').hide().fadeIn();
$("#new_comment")[0].reset();
$('<%= escape_javascript(render(:partial => "comments/countcomments")) %>').replaceAll('#total');

app/views/comments/destroy.js.erb
$("#<%= dom_id @comment %>").remove();
$('<%= escape_javascript(render(:partial => "comments/countcomments")) %>').replaceAll('#total');

app/views/home/index.html.erb
<div id="sidebar">sidebar</div>
  <div id="main">
	<div id="content">
      <% @posts.each do |post| %>

     <strong><%= link_to_unless_current post.title, post %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <%= post.comments.count %><br/>
     由:<%= post.user.username %>在
  <%=case post.category
                         when 0
                                     "日志"
                         when 1
                                    "技术"
                         when 2
                                     "转载"
                              else "无"
       end %>中发起
    <br/>
<% end %>
<br/>
<%= paginate @posts %>
</div>

    <div id="tags"><!--标签云-->
    TAGS: <% tag_cloud @tags, %w(css1 css2 css3 css4) do |tag, css_class| %>
      &nbsp;&nbsp;
    <%= link_to tag.name, {:action => :tag, :id => tag.name }, :class => css_class %>
     <% end %></div>

     <div id="help">
      <ul>
        <li><%=link_to' 关于本站'%></li>
        <li><%=link_to' 意见反馈'%></li>
        <li><%=link_to' bug修复'%></li>
      </ul>
    </div>
    <div id="sort">sort</div>

</div>

app/views/home/tag.erb
<table>
  <tr>
    <td>title</td>
    <td>content</td>
  </tr>

<% @posts.each do |post| %>
<tr>
    <td><%= post.title %></td>
    <td>content<%= post.content %></td>
  <br/>
</tr>
<% end %>
</table>

<%= link_to 'Back to Home', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <title>myblog</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body >
<div id="top">
  <div id="navigation">
             <ul>
               <li><%= link_to '首页', root_path %></li>
              <% if user_signed_in? %>
              <li><%= link_to current_user.username,posts_path %></li>
              <li><%= link_to('密码修改', edit_registration_path(:user)) %></li>
              <li><%= link_to '个人信息修改', edit_profile_path(current_user) %></li>
              <li><%= link_to "退出", destroy_user_session_path %></li>
  <% else %>
                   <li><%= link_to "注册", new_user_registration_path %> or <%= link_to "登录", new_user_session_path %></li>
  <% end %>
             </ul>
      </div>
</div>
<p class="notice"><%=notice%></p>
<p class="alert"><%=alert%></p>
  <%= yield %>
<div id="footer"> Copyright, 2010 gsm1022.com &nbsp;&#8226;&nbsp; Design by somboy </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |post_form| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= post_form.label :title %><br />
    <%= post_form.text_field :title %>
  </div>

   <div class="field">
    <%= post_form.label :category %>
    <%= post_form.select(:category,options_for_select({ "日志" => "0", "技术" => "1","转载" => "2"})) %>
  </div>

  <div class="field">
    <%= post_form.label :content %><br />
    <%= post_form.text_area :content, :cols =>25, :rows => 10%>
  </div>

     <div class="field">
    <%= post_form.label :tags,'标签' %><br />
    <%= post_form.text_field :tag_list,:size=>'40' %>*多个标签以","隔开
    </div>

  <div class="actions">
    <%= post_form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>
<br />
<%= link_to 'New Post', new_post_path %>
<br/>

<% @posts.each do |post| %>
    <b>username:</b><%= post.user.username %>
     <b>title:</b><%= link_to_unless_current post.title, post %>
     <b>content:</b><%=post.content %>
     <b>Category:</b>
  <%=case post.category
                         when 0
                                     "日志"
                         when 1
                                    "技术"
                         when 2
                                     "转载"
                              else "无"
       end %>

 <b>评论数量: </b><%= post.comments.count %>

     <%= link_to 'Edit', edit_post_path(post) %>|
     <%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %>

      </p>
<% end %>
<br/>

 <!--标签云-->
    <div style="padding:20px">
    tags: <% tag_cloud @tags, %w(css1 css2 css3 css4) do |tag, css_class| %>
    <%= link_to tag.name, {:action => :tag, :id => tag.name }, :class => css_class %>
     <% end %>
</div>


<%= paginate @posts%>
<%= form_for @search, url: posts_path, method: :get do |f| %>
    <p>search</p>
            <%= f.label :title %>
            <%= f.text_field :title_contains %>
            <%= f.submit %>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= render 'form' %>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p><strong><%= @post.title %></strong></p>
<br/>
 <p>
  <%= @post.content %>
</p>
  <%= time_ago_in_words(@post.created_at) %>由<%= @post.user.username %>在
<%=case @post.category
                         when 0
                                     "日志"
                         when 1
                                    "技术"
                         when 2
                                     "转载"
                              else "无"
        end %>中发起

<br/><br/><br/><br/><br/><br/>
<div id="total">共有<%= (@post.comments.count)%>条回复<br/></div>


<table id="comments">
  <tr>
  <td>username</td>
  <td>content</td>
  <td>time</td>
  <td>operation</td>
</tr>
      <%= render @post.comments%>
  </table>

<h2>Add a comment:</h2> <br/>
<%= form_for([@post,@post.comments.build], :remote=>true) do |f| %>
<div class="field">
    <%= f.text_area :body, :cols => 20, :rows => 10%>
</div>
<div class="actions">
    <%= f.submit %>
</div>

<% end %>
<br />
<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %>

app/views/posts/tag.erb
<table>
  <tr>
    <td>title</td>
    <td>content</td>
  </tr>

<% @posts.each do |post| %>
<tr>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
  <br/>
</tr>
<% end %>
</table>

<%= link_to 'Back to Posts', posts_path %>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |profile_form| %>
  <% if @profile.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
    <% @profile.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div>
  <select name="profile[gender]">
   <% if  @profile.gender==1%>
  <option value=1 selected="">男</option>
   <option value=0>女</option>
  <%else%>
  <option value=1 >男</option>
  <option value=0 selected="">女</option>
  <%end%>
   </select>
  </div>

  <div class="field">
    <%= profile_form.label :birth_year %><br />
    <%= profile_form.text_field :birth_year %><br />
  </div>
    <div class="field">
    <%= profile_form.label :birth_month %><br />
      <%= profile_form.text_field :birth_month %><br />
  </div>
    <div class="field">
    <%= profile_form.label :birth_day %><br />
      <%= profile_form.text_field :birth_day %><br />
  </div>

 <div class="actions">
    <%= profile_form.submit %>
  </div>

<% end %>

app/views/profiles/edit.html.erb
 <p>
  <b>Name:</b>
   <b><%= @profile.user.username %></b>
</p>

<%= render 'form' %>

<!--debug(@profile) %>-->

<%= link_to 'Back', posts_path %>

app/views/profiles/index.html.erb
<p><%= link_to 'Back to posts', posts_path %></p>
<%= link_to "profile",edit_profile_path(current_user) %>

app/views/profiles/new.html.erb
<p><%= link_to 'Back to posts', posts_path %></p>

app/views/profiles/show.html.erb
<p><%= link_to 'Back to posts', posts_path %></p>
<%= link_to "profile",edit_profile_path(current_user) %>